# Generated by Django 3.2.3 on 2025-03-08 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='achievementcat',
            options={'verbose_name': 'Achievement Cat', 'verbose_name_plural': 'Achievement Cats'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name'], 'verbose_name': 'Cat', 'verbose_name_plural': 'Cats'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(help_text='Name of the achievement.  Keep it concise and descriptive.', max_length=64, verbose_name='Achievement Name'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.achievement', verbose_name='Achievement'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat', verbose_name='Cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(help_text='Achievements earned by this cat.', through='cats.AchievementCat', to='cats.Achievement', verbose_name='Achievements'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(help_text='The year the cat was born.', verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(help_text="The cat's color.", max_length=16, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, help_text='An image of the cat.  Recommended size: 200x200 pixels.', null=True, upload_to='cats/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(help_text="The cat's name.", max_length=16, verbose_name='Cat Name'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this cat.', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementcat',
            unique_together={('achievement', 'cat')},
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.CheckConstraint(check=models.Q(('birth_year__gt', 1900), ('birth_year__lt', 2100)), name='birth_year_reasonable'),
        ),
    ]
